name: API Tests CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pre-commit black ruff

      - name: Run pre-commit lint (Black + Ruff)
        run: pre-commit run --all-files

  full-regression:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/workflow-template.yml
    with:
      artifact_name: allure-report-full
      test_marker: ""
    permissions:
      contents: write

  smoke-tests:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/workflow-template.yml
    with:
      artifact_name: allure-report-smoke
      test_marker: "smoke"
    permissions:
      contents: write

  deploy:
    needs: full-regression
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Download Allure report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report-full
          path: reports/allure-report

      - name: Upload Allure report to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports/allure-report

      - name: Deploy Allure report to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment

      - name: Add Allure Report link to job summary
        run: |
          echo "## 📊 [Allure Report — click to view](https://vpaikina.github.io/book-library-api-tests/)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "[![Allure Report](https://img.shields.io/badge/Allure--Report-blue?logo=allure&label=Allure%20Report)](https://vpaikina.github.io/book-library-api-tests/)" >> $GITHUB_STEP_SUMMARY

